/*
 * CrowdStrike API Specification
 *
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: 2026-01-28T00:00:04Z
 * 
 * Generated by: https://openapi-generator.tech
 */


use async_trait::async_trait;
use reqwest;
use std::sync::Arc;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration};
use crate::apis::ContentType;

#[async_trait]
pub trait DownloadsApiApi: Send + Sync {

    /// GET /csdownloads/entities/files/download/v1
    ///
    /// 
    async fn download_file(&self,  params: DownloadFileParams ) -> Result<models::ModelsEntitiesResponse, Error<DownloadFileError>>;

    /// GET /csdownloads/entities/files/enumerate/v1
    ///
    /// 
    async fn enumerate_file(&self,  params: EnumerateFileParams ) -> Result<models::ModelsEntitiesResponse, Error<EnumerateFileError>>;

    /// GET /csdownloads/combined/files-download/v1
    ///
    /// 
    async fn fetch_files_download_info(&self,  params: FetchFilesDownloadInfoParams ) -> Result<models::ModelsEntitiesResponse, Error<FetchFilesDownloadInfoError>>;

    /// GET /csdownloads/combined/files-download/v2
    ///
    /// 
    async fn fetch_files_download_info_v2(&self,  params: FetchFilesDownloadInfoV2Params ) -> Result<models::ModelsCombinedFilesDownloadResponse, Error<FetchFilesDownloadInfoV2Error>>;
}

pub struct DownloadsApiApiClient {
    configuration: Arc<configuration::Configuration>
}

impl DownloadsApiApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}


/// struct for passing parameters to the method [`DownloadsApiApi::download_file`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct DownloadFileParams {
    /// Name of the file to be downloaded
    pub file_name: String,
    /// Version of the file to be downloaded
    pub file_version: String
}

/// struct for passing parameters to the method [`DownloadsApiApi::enumerate_file`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct EnumerateFileParams {
    /// Apply filtering on file name
    pub file_name: Option<String>,
    /// Apply filtering on file version
    pub file_version: Option<String>,
    /// Apply filtering on file platform
    pub platform: Option<String>,
    /// Apply filtering on operating system
    pub os: Option<String>,
    /// Apply filtering on architecture
    pub arch: Option<String>,
    /// Apply filtering on file category
    pub category: Option<String>
}

/// struct for passing parameters to the method [`DownloadsApiApi::fetch_files_download_info`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct FetchFilesDownloadInfoParams {
    /// Search files using various filters using query in Falcon Query Language (FQL). Supported filters: arch,category,file_name,file_version,os
    pub filter: Option<String>,
    /// The fields to sort records on. Supported columns:  - `arch` - `category` - `file_name` - `file_version` - `os`
    pub sort: Option<String>
}

/// struct for passing parameters to the method [`DownloadsApiApi::fetch_files_download_info_v2`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct FetchFilesDownloadInfoV2Params {
    /// Search files using various filters. Supported filters: arch,category,file_name,file_version,os
    pub filter: Option<String>,
    /// The fields to sort records on. Supported columns:  - `arch` - `category` - `file_name` - `file_version` - `os`
    pub sort: Option<String>,
    /// The upper-bound on the number of records to retrieve. Maximum limit: 100.
    pub limit: Option<i32>,
    /// The offset from where to begin. Maximum offset = 1000 - limit.
    pub offset: Option<i32>
}


#[async_trait]
impl DownloadsApiApi for DownloadsApiApiClient {
    async fn download_file(&self,  params: DownloadFileParams ) -> Result<models::ModelsEntitiesResponse, Error<DownloadFileError>> {
        
        let DownloadFileParams {
            file_name,
            file_version,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/csdownloads/entities/files/download/v1", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.query(&[("file_name", &file_name.to_string())]);
        local_var_req_builder = local_var_req_builder.query(&[("file_version", &file_version.to_string())]);
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ModelsEntitiesResponse`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ModelsEntitiesResponse`")))),
            }
        } else {
            let local_var_entity: Option<DownloadFileError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn enumerate_file(&self,  params: EnumerateFileParams ) -> Result<models::ModelsEntitiesResponse, Error<EnumerateFileError>> {
        
        let EnumerateFileParams {
            file_name,
            file_version,
            platform,
            os,
            arch,
            category,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/csdownloads/entities/files/enumerate/v1", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = file_name {
            local_var_req_builder = local_var_req_builder.query(&[("file_name", &param_value.to_string())]);
        }
        if let Some(ref param_value) = file_version {
            local_var_req_builder = local_var_req_builder.query(&[("file_version", &param_value.to_string())]);
        }
        if let Some(ref param_value) = platform {
            local_var_req_builder = local_var_req_builder.query(&[("platform", &param_value.to_string())]);
        }
        if let Some(ref param_value) = os {
            local_var_req_builder = local_var_req_builder.query(&[("os", &param_value.to_string())]);
        }
        if let Some(ref param_value) = arch {
            local_var_req_builder = local_var_req_builder.query(&[("arch", &param_value.to_string())]);
        }
        if let Some(ref param_value) = category {
            local_var_req_builder = local_var_req_builder.query(&[("category", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ModelsEntitiesResponse`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ModelsEntitiesResponse`")))),
            }
        } else {
            let local_var_entity: Option<EnumerateFileError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn fetch_files_download_info(&self,  params: FetchFilesDownloadInfoParams ) -> Result<models::ModelsEntitiesResponse, Error<FetchFilesDownloadInfoError>> {
        
        let FetchFilesDownloadInfoParams {
            filter,
            sort,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/csdownloads/combined/files-download/v1", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = filter {
            local_var_req_builder = local_var_req_builder.query(&[("filter", &param_value.to_string())]);
        }
        if let Some(ref param_value) = sort {
            local_var_req_builder = local_var_req_builder.query(&[("sort", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ModelsEntitiesResponse`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ModelsEntitiesResponse`")))),
            }
        } else {
            let local_var_entity: Option<FetchFilesDownloadInfoError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn fetch_files_download_info_v2(&self,  params: FetchFilesDownloadInfoV2Params ) -> Result<models::ModelsCombinedFilesDownloadResponse, Error<FetchFilesDownloadInfoV2Error>> {
        
        let FetchFilesDownloadInfoV2Params {
            filter,
            sort,
            limit,
            offset,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/csdownloads/combined/files-download/v2", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = filter {
            local_var_req_builder = local_var_req_builder.query(&[("filter", &param_value.to_string())]);
        }
        if let Some(ref param_value) = sort {
            local_var_req_builder = local_var_req_builder.query(&[("sort", &param_value.to_string())]);
        }
        if let Some(ref param_value) = limit {
            local_var_req_builder = local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = offset {
            local_var_req_builder = local_var_req_builder.query(&[("offset", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ModelsCombinedFilesDownloadResponse`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ModelsCombinedFilesDownloadResponse`")))),
            }
        } else {
            let local_var_entity: Option<FetchFilesDownloadInfoV2Error> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

}

/// struct for typed errors of method [`DownloadsApiApi::download_file`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DownloadFileError {
    Status400(models::ModelsEntitiesResponse),
    Status401(models::ModelsEntitiesResponse),
    Status403(models::ModelsEntitiesResponse),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::ModelsEntitiesResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`DownloadsApiApi::enumerate_file`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EnumerateFileError {
    Status400(models::ModelsEntitiesResponse),
    Status401(models::ModelsEntitiesResponse),
    Status403(models::ModelsEntitiesResponse),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::ModelsEntitiesResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`DownloadsApiApi::fetch_files_download_info`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchFilesDownloadInfoError {
    Status400(models::ModelsEntitiesResponse),
    Status401(models::ModelsEntitiesResponse),
    Status403(models::ModelsEntitiesResponse),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::ModelsEntitiesResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`DownloadsApiApi::fetch_files_download_info_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchFilesDownloadInfoV2Error {
    Status400(models::ModelsEntitiesResponse),
    Status401(models::ModelsEntitiesResponse),
    Status403(models::ModelsEntitiesResponse),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::ModelsEntitiesResponse),
    UnknownValue(serde_json::Value),
}

