/*
 * CrowdStrike API Specification
 *
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: 2026-01-28T00:00:04Z
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DomainSsIoaExclusionsNewRuleReqV2 {
    #[serde(rename = "aid")]
    pub aid: String,
    #[serde(rename = "command_line")]
    pub command_line: String,
    #[serde(rename = "grandparent_command_line")]
    pub grandparent_command_line: String,
    #[serde(rename = "grandparent_image_file_name")]
    pub grandparent_image_file_name: String,
    #[serde(rename = "image_file_name")]
    pub image_file_name: String,
    #[serde(rename = "parent_command_line")]
    pub parent_command_line: String,
    #[serde(rename = "parent_image_file_name")]
    pub parent_image_file_name: String,
}

impl DomainSsIoaExclusionsNewRuleReqV2 {
    pub fn new(aid: String, command_line: String, grandparent_command_line: String, grandparent_image_file_name: String, image_file_name: String, parent_command_line: String, parent_image_file_name: String) -> DomainSsIoaExclusionsNewRuleReqV2 {
        DomainSsIoaExclusionsNewRuleReqV2 {
            aid,
            command_line,
            grandparent_command_line,
            grandparent_image_file_name,
            image_file_name,
            parent_command_line,
            parent_image_file_name,
        }
    }
}

