/*
 * CrowdStrike API Specification
 *
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: 2026-01-28T00:00:04Z
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2Definition {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "nodeRegistry")]
    pub node_registry: std::collections::HashMap<String, String>,
    #[serde(rename = "parent")]
    pub parent: models::V2Model,
    #[serde(rename = "trigger")]
    pub trigger: models::V2Trigger,
    #[serde(rename = "uniqNodeSeen")]
    pub uniq_node_seen: std::collections::HashMap<String, bool>,
    #[serde(rename = "actions", skip_serializing_if = "Option::is_none")]
    pub actions: Option<std::collections::HashMap<String, models::V2Activity>>,
    #[serde(rename = "conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<std::collections::HashMap<String, models::V2Condition>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "disconnected_nodes", skip_serializing_if = "Option::is_none")]
    pub disconnected_nodes: Option<Vec<String>>,
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<Vec<String>>,
    #[serde(rename = "loops", skip_serializing_if = "Option::is_none")]
    pub loops: Option<std::collections::HashMap<String, models::V2Loop>>,
    #[serde(rename = "multi_instance", skip_serializing_if = "Option::is_none")]
    pub multi_instance: Option<bool>,
    #[serde(rename = "output_fields", skip_serializing_if = "Option::is_none")]
    pub output_fields: Option<Vec<String>>,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<models::V2Parameters>,
    #[serde(rename = "provision_on_install", skip_serializing_if = "Option::is_none")]
    pub provision_on_install: Option<bool>,
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "use_cases", skip_serializing_if = "Option::is_none")]
    pub use_cases: Option<Vec<String>>,
    #[serde(rename = "vendors", skip_serializing_if = "Option::is_none")]
    pub vendors: Option<Vec<String>>,
}

impl V2Definition {
    pub fn new(name: String, node_registry: std::collections::HashMap<String, String>, parent: models::V2Model, trigger: models::V2Trigger, uniq_node_seen: std::collections::HashMap<String, bool>) -> V2Definition {
        V2Definition {
            name,
            node_registry,
            parent,
            trigger,
            uniq_node_seen,
            actions: None,
            conditions: None,
            description: None,
            disconnected_nodes: None,
            labels: None,
            loops: None,
            multi_instance: None,
            output_fields: None,
            parameters: None,
            provision_on_install: None,
            summary: None,
            r#type: None,
            use_cases: None,
            vendors: None,
        }
    }
}

