/*
 * CrowdStrike API Specification
 *
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: 2026-01-28T00:00:04Z
 *
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;

use async_trait::async_trait;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

use super::{Error, configuration};
use crate::experimental::{
    apis::{ContentType, ResponseContent},
    models,
};

#[async_trait]
pub trait CloudConnectAwsApi: Send + Sync {
    /// POST /cloud-connect-aws/entities/settings/v1
    ///
    ///
    async fn create_or_update_aws_settings(
        &self,
        params: CreateOrUpdateAwsSettingsParams,
    ) -> Result<models::ModelsCustomerConfigurationsV1, Error<CreateOrUpdateAwsSettingsError>>;

    /// DELETE /cloud-connect-aws/entities/accounts/v1
    ///
    ///
    async fn delete_aws_accounts(
        &self,
        params: DeleteAwsAccountsParams,
    ) -> Result<models::ModelsBaseResponseV1, Error<DeleteAwsAccountsError>>;

    /// GET /cloud-connect-aws/entities/accounts/v1
    ///
    ///
    async fn get_aws_accounts(
        &self,
        params: GetAwsAccountsParams,
    ) -> Result<models::ModelsAwsAccountsV1, Error<GetAwsAccountsError>>;

    /// GET /cloud-connect-aws/combined/settings/v1
    ///
    ///
    async fn get_aws_settings(
        &self,
    ) -> Result<models::ModelsCustomerConfigurationsV1, Error<GetAwsSettingsError>>;

    /// POST /cloud-connect-aws/entities/accounts/v1
    ///
    ///
    async fn provision_aws_accounts(
        &self,
        params: ProvisionAwsAccountsParams,
    ) -> Result<models::ModelsAwsAccountsV1, Error<ProvisionAwsAccountsError>>;

    /// GET /cloud-connect-aws/combined/accounts/v1
    ///
    ///
    async fn query_aws_accounts(
        &self,
        params: QueryAwsAccountsParams,
    ) -> Result<models::ModelsAwsAccountsV1, Error<QueryAwsAccountsError>>;

    /// GET /cloud-connect-aws/queries/accounts/v1
    ///
    ///
    async fn query_aws_accounts_for_ids(
        &self,
        params: QueryAwsAccountsForIdsParams,
    ) -> Result<models::MsaQueryResponse, Error<QueryAwsAccountsForIdsError>>;

    /// PATCH /cloud-connect-aws/entities/accounts/v1
    ///
    ///
    async fn update_aws_accounts(
        &self,
        params: UpdateAwsAccountsParams,
    ) -> Result<models::ModelsAwsAccountsV1, Error<UpdateAwsAccountsError>>;

    /// POST /cloud-connect-aws/entities/verify-account-access/v1
    ///
    ///
    async fn verify_aws_account_access(
        &self,
        params: VerifyAwsAccountAccessParams,
    ) -> Result<models::ModelsVerifyAccessResponseV1, Error<VerifyAwsAccountAccessError>>;
}

pub struct CloudConnectAwsApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl CloudConnectAwsApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

/// struct for passing parameters to the method [`CloudConnectAwsApi::create_or_update_aws_settings`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct CreateOrUpdateAwsSettingsParams {
    pub body: models::ModelsModifyAwsCustomerSettingsV1,
}

/// struct for passing parameters to the method [`CloudConnectAwsApi::delete_aws_accounts`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct DeleteAwsAccountsParams {
    /// IDs of accounts to remove
    pub ids: Vec<String>,
}

/// struct for passing parameters to the method [`CloudConnectAwsApi::get_aws_accounts`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct GetAwsAccountsParams {
    /// IDs of accounts to retrieve details
    pub ids: Vec<String>,
}

/// struct for passing parameters to the method [`CloudConnectAwsApi::provision_aws_accounts`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct ProvisionAwsAccountsParams {
    pub body: models::ModelsCreateAwsAccountsV1,
    /// Mode for provisioning. Allowed values are `manual` or `cloudformation`. Defaults to manual if not defined.
    pub mode: Option<String>,
}

/// struct for passing parameters to the method [`CloudConnectAwsApi::query_aws_accounts`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct QueryAwsAccountsParams {
    /// The maximum records to return. [1-1000]. Defaults to 100.
    pub limit: Option<i32>,
    /// The offset to start retrieving records from
    pub offset: Option<i32>,
    /// The property to sort by (e.g. alias.desc or state.asc)
    pub sort: Option<String>,
    /// The filter expression that should be used to limit the results
    pub filter: Option<String>,
}

/// struct for passing parameters to the method [`CloudConnectAwsApi::query_aws_accounts_for_ids`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct QueryAwsAccountsForIdsParams {
    /// The maximum records to return. [1-1000]. Defaults to 100.
    pub limit: Option<i32>,
    /// The offset to start retrieving records from
    pub offset: Option<i32>,
    /// The property to sort by (e.g. alias.desc or state.asc)
    pub sort: Option<String>,
    /// The filter expression that should be used to limit the results
    pub filter: Option<String>,
}

/// struct for passing parameters to the method [`CloudConnectAwsApi::update_aws_accounts`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct UpdateAwsAccountsParams {
    pub body: models::ModelsUpdateAwsAccountsV1,
}

/// struct for passing parameters to the method [`CloudConnectAwsApi::verify_aws_account_access`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct VerifyAwsAccountAccessParams {
    /// IDs of accounts to verify access on
    pub ids: Vec<String>,
}

#[async_trait]
impl CloudConnectAwsApi for CloudConnectAwsApiClient {
    async fn create_or_update_aws_settings(
        &self,
        params: CreateOrUpdateAwsSettingsParams,
    ) -> Result<models::ModelsCustomerConfigurationsV1, Error<CreateOrUpdateAwsSettingsError>> {
        let CreateOrUpdateAwsSettingsParams { body } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/cloud-connect-aws/entities/settings/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&body);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::ModelsCustomerConfigurationsV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ModelsCustomerConfigurationsV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<CreateOrUpdateAwsSettingsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn delete_aws_accounts(
        &self,
        params: DeleteAwsAccountsParams,
    ) -> Result<models::ModelsBaseResponseV1, Error<DeleteAwsAccountsError>> {
        let DeleteAwsAccountsParams { ids } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/cloud-connect-aws/entities/accounts/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        local_var_req_builder = match "multi" {
            "multi" => local_var_req_builder.query(
                &ids.into_iter()
                    .map(|p| ("ids".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => local_var_req_builder.query(&[(
                "ids",
                &ids.into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::ModelsBaseResponseV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ModelsBaseResponseV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<DeleteAwsAccountsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn get_aws_accounts(
        &self,
        params: GetAwsAccountsParams,
    ) -> Result<models::ModelsAwsAccountsV1, Error<GetAwsAccountsError>> {
        let GetAwsAccountsParams { ids } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/cloud-connect-aws/entities/accounts/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = match "multi" {
            "multi" => local_var_req_builder.query(
                &ids.into_iter()
                    .map(|p| ("ids".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => local_var_req_builder.query(&[(
                "ids",
                &ids.into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::ModelsAwsAccountsV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ModelsAwsAccountsV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<GetAwsAccountsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn get_aws_settings(
        &self,
    ) -> Result<models::ModelsCustomerConfigurationsV1, Error<GetAwsSettingsError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/cloud-connect-aws/combined/settings/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::ModelsCustomerConfigurationsV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ModelsCustomerConfigurationsV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<GetAwsSettingsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn provision_aws_accounts(
        &self,
        params: ProvisionAwsAccountsParams,
    ) -> Result<models::ModelsAwsAccountsV1, Error<ProvisionAwsAccountsError>> {
        let ProvisionAwsAccountsParams { body, mode } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/cloud-connect-aws/entities/accounts/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref param_value) = mode {
            local_var_req_builder =
                local_var_req_builder.query(&[("mode", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&body);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::ModelsAwsAccountsV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ModelsAwsAccountsV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<ProvisionAwsAccountsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn query_aws_accounts(
        &self,
        params: QueryAwsAccountsParams,
    ) -> Result<models::ModelsAwsAccountsV1, Error<QueryAwsAccountsError>> {
        let QueryAwsAccountsParams {
            limit,
            offset,
            sort,
            filter,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/cloud-connect-aws/combined/accounts/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = limit {
            local_var_req_builder =
                local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = offset {
            local_var_req_builder =
                local_var_req_builder.query(&[("offset", &param_value.to_string())]);
        }
        if let Some(ref param_value) = sort {
            local_var_req_builder =
                local_var_req_builder.query(&[("sort", &param_value.to_string())]);
        }
        if let Some(ref param_value) = filter {
            local_var_req_builder =
                local_var_req_builder.query(&[("filter", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::ModelsAwsAccountsV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ModelsAwsAccountsV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<QueryAwsAccountsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn query_aws_accounts_for_ids(
        &self,
        params: QueryAwsAccountsForIdsParams,
    ) -> Result<models::MsaQueryResponse, Error<QueryAwsAccountsForIdsError>> {
        let QueryAwsAccountsForIdsParams {
            limit,
            offset,
            sort,
            filter,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/cloud-connect-aws/queries/accounts/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = limit {
            local_var_req_builder =
                local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = offset {
            local_var_req_builder =
                local_var_req_builder.query(&[("offset", &param_value.to_string())]);
        }
        if let Some(ref param_value) = sort {
            local_var_req_builder =
                local_var_req_builder.query(&[("sort", &param_value.to_string())]);
        }
        if let Some(ref param_value) = filter {
            local_var_req_builder =
                local_var_req_builder.query(&[("filter", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::MsaQueryResponse`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::MsaQueryResponse`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<QueryAwsAccountsForIdsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn update_aws_accounts(
        &self,
        params: UpdateAwsAccountsParams,
    ) -> Result<models::ModelsAwsAccountsV1, Error<UpdateAwsAccountsError>> {
        let UpdateAwsAccountsParams { body } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/cloud-connect-aws/entities/accounts/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PATCH, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&body);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::ModelsAwsAccountsV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ModelsAwsAccountsV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<UpdateAwsAccountsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn verify_aws_account_access(
        &self,
        params: VerifyAwsAccountAccessParams,
    ) -> Result<models::ModelsVerifyAccessResponseV1, Error<VerifyAwsAccountAccessError>> {
        let VerifyAwsAccountAccessParams { ids } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/cloud-connect-aws/entities/verify-account-access/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = match "multi" {
            "multi" => local_var_req_builder.query(
                &ids.into_iter()
                    .map(|p| ("ids".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => local_var_req_builder.query(&[(
                "ids",
                &ids.into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::ModelsVerifyAccessResponseV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ModelsVerifyAccessResponseV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<VerifyAwsAccountAccessError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`CloudConnectAwsApi::create_or_update_aws_settings`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateOrUpdateAwsSettingsError {
    Status400(models::ModelsCustomerConfigurationsV1),
    Status403(models::MsaReplyMetaOnly),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::ModelsCustomerConfigurationsV1),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`CloudConnectAwsApi::delete_aws_accounts`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteAwsAccountsError {
    Status400(models::ModelsBaseResponseV1),
    Status403(models::MsaReplyMetaOnly),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::ModelsBaseResponseV1),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`CloudConnectAwsApi::get_aws_accounts`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAwsAccountsError {
    Status400(models::ModelsAwsAccountsV1),
    Status403(models::MsaReplyMetaOnly),
    Status404(models::ModelsAwsAccountsV1),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::ModelsAwsAccountsV1),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`CloudConnectAwsApi::get_aws_settings`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAwsSettingsError {
    Status400(models::ModelsCustomerConfigurationsV1),
    Status403(models::MsaReplyMetaOnly),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::ModelsCustomerConfigurationsV1),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`CloudConnectAwsApi::provision_aws_accounts`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ProvisionAwsAccountsError {
    Status400(models::ModelsAwsAccountsV1),
    Status403(models::MsaReplyMetaOnly),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::ModelsAwsAccountsV1),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`CloudConnectAwsApi::query_aws_accounts`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QueryAwsAccountsError {
    Status400(models::ModelsAwsAccountsV1),
    Status403(models::MsaReplyMetaOnly),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::ModelsAwsAccountsV1),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`CloudConnectAwsApi::query_aws_accounts_for_ids`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QueryAwsAccountsForIdsError {
    Status400(models::MsaQueryResponse),
    Status403(models::MsaReplyMetaOnly),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::MsaQueryResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`CloudConnectAwsApi::update_aws_accounts`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateAwsAccountsError {
    Status400(models::ModelsAwsAccountsV1),
    Status403(models::MsaReplyMetaOnly),
    Status404(models::ModelsAwsAccountsV1),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::ModelsAwsAccountsV1),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`CloudConnectAwsApi::verify_aws_account_access`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum VerifyAwsAccountAccessError {
    Status400(models::ModelsVerifyAccessResponseV1),
    Status403(models::MsaReplyMetaOnly),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::ModelsVerifyAccessResponseV1),
    UnknownValue(serde_json::Value),
}
