/*
 * CrowdStrike API Specification
 *
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: 2026-01-28T00:00:04Z
 *
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;

use async_trait::async_trait;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

use super::{Error, configuration};
use crate::experimental::{
    apis::{ContentType, ResponseContent},
    models,
};

#[async_trait]
pub trait CloudAzureRegistrationApi: Send + Sync {
    /// POST /cloud-security-registration-azure/entities/registrations/v1
    ///
    ///
    async fn cloud_registration_azure_create_registration(
        &self,
        params: CloudRegistrationAzureCreateRegistrationParams,
    ) -> Result<
        models::AzureAzureRegistrationResponseExtV1,
        Error<CloudRegistrationAzureCreateRegistrationError>,
    >;

    /// DELETE /cloud-security-registration-azure/entities/accounts/legacy/v1
    ///
    ///
    async fn cloud_registration_azure_delete_legacy_subscription(
        &self,
        params: CloudRegistrationAzureDeleteLegacySubscriptionParams,
    ) -> Result<
        models::AzureLegacySubscriptionDeleteResponseExtV1,
        Error<CloudRegistrationAzureDeleteLegacySubscriptionError>,
    >;

    /// DELETE /cloud-security-registration-azure/entities/registrations/v1
    ///
    ///
    async fn cloud_registration_azure_delete_registration(
        &self,
        params: CloudRegistrationAzureDeleteRegistrationParams,
    ) -> Result<
        models::AzureDeleteRegistrationResponseExtV1,
        Error<CloudRegistrationAzureDeleteRegistrationError>,
    >;

    /// POST /cloud-security-registration-azure/entities/scripts/v1
    ///
    ///
    async fn cloud_registration_azure_download_script(
        &self,
        params: CloudRegistrationAzureDownloadScriptParams,
    ) -> Result<
        models::AzureAzureProvisionGetAccountScriptResponseV1,
        Error<CloudRegistrationAzureDownloadScriptError>,
    >;

    /// GET /cloud-security-registration-azure/entities/registrations/v1
    ///
    ///
    async fn cloud_registration_azure_get_registration(
        &self,
        params: CloudRegistrationAzureGetRegistrationParams,
    ) -> Result<
        models::AzureAzureRegistrationResponseExtV1,
        Error<CloudRegistrationAzureGetRegistrationError>,
    >;

    /// POST /cloud-security-registration-azure/entities/registrations/healthcheck/v1
    ///
    ///
    async fn cloud_registration_azure_trigger_health_check(
        &self,
        params: CloudRegistrationAzureTriggerHealthCheckParams,
    ) -> Result<
        models::AzureHealthCheckTriggerResponseExtV1,
        Error<CloudRegistrationAzureTriggerHealthCheckError>,
    >;

    /// PATCH /cloud-security-registration-azure/entities/registrations/v1
    ///
    ///
    async fn cloud_registration_azure_update_registration(
        &self,
        params: CloudRegistrationAzureUpdateRegistrationParams,
    ) -> Result<
        models::AzureAzureRegistrationResponseExtV1,
        Error<CloudRegistrationAzureUpdateRegistrationError>,
    >;

    /// POST /cloud-security-registration-azure/entities/registrations/validate/v1
    ///
    ///
    async fn cloud_registration_azure_validate_registration(
        &self,
        params: CloudRegistrationAzureValidateRegistrationParams,
    ) -> Result<
        models::AzureRegistrationValidateResponseV1,
        Error<CloudRegistrationAzureValidateRegistrationError>,
    >;

    /// GET /cloud-security-registration-azure/entities/scripts/v1
    ///
    ///
    async fn download_azure_script(
        &self,
        params: DownloadAzureScriptParams,
    ) -> Result<(), Error<DownloadAzureScriptError>>;
}

pub struct CloudAzureRegistrationApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl CloudAzureRegistrationApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

/// struct for passing parameters to the method [`CloudAzureRegistrationApi::cloud_registration_azure_create_registration`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct CloudRegistrationAzureCreateRegistrationParams {
    pub body: models::AzureAzureRegistrationCreateRequestExtV1,
}

/// struct for passing parameters to the method [`CloudAzureRegistrationApi::cloud_registration_azure_delete_legacy_subscription`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct CloudRegistrationAzureDeleteLegacySubscriptionParams {
    pub body: models::AzureLegacySubscriptionDeleteRequestExtV1,
}

/// struct for passing parameters to the method [`CloudAzureRegistrationApi::cloud_registration_azure_delete_registration`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct CloudRegistrationAzureDeleteRegistrationParams {
    /// Azure tenant IDs
    pub tenant_ids: Vec<String>,
}

/// struct for passing parameters to the method [`CloudAzureRegistrationApi::cloud_registration_azure_download_script`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct CloudRegistrationAzureDownloadScriptParams {
    pub body: models::AzureAzureDownloadScriptRequestV1,
}

/// struct for passing parameters to the method [`CloudAzureRegistrationApi::cloud_registration_azure_get_registration`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct CloudRegistrationAzureGetRegistrationParams {
    /// Tenant ID
    pub tenant_id: String,
}

/// struct for passing parameters to the method [`CloudAzureRegistrationApi::cloud_registration_azure_trigger_health_check`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct CloudRegistrationAzureTriggerHealthCheckParams {
    /// Azure tenant IDs
    pub tenant_ids: Option<Vec<String>>,
}

/// struct for passing parameters to the method [`CloudAzureRegistrationApi::cloud_registration_azure_update_registration`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct CloudRegistrationAzureUpdateRegistrationParams {
    pub body: models::AzureAzureRegistrationUpdateRequestExtV1,
}

/// struct for passing parameters to the method [`CloudAzureRegistrationApi::cloud_registration_azure_validate_registration`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct CloudRegistrationAzureValidateRegistrationParams {
    /// Azure tenant ID to be validated
    pub tenant_id: String,
    /// Azure deployment stack name to be validated
    pub stack_name: Option<String>,
}

/// struct for passing parameters to the method [`CloudAzureRegistrationApi::download_azure_script`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct DownloadAzureScriptParams {
    /// Azure tenant ID
    pub tenant_id: String,
}

#[async_trait]
impl CloudAzureRegistrationApi for CloudAzureRegistrationApiClient {
    async fn cloud_registration_azure_create_registration(
        &self,
        params: CloudRegistrationAzureCreateRegistrationParams,
    ) -> Result<
        models::AzureAzureRegistrationResponseExtV1,
        Error<CloudRegistrationAzureCreateRegistrationError>,
    > {
        let CloudRegistrationAzureCreateRegistrationParams { body } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/cloud-security-registration-azure/entities/registrations/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&body);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::AzureAzureRegistrationResponseExtV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AzureAzureRegistrationResponseExtV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<CloudRegistrationAzureCreateRegistrationError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn cloud_registration_azure_delete_legacy_subscription(
        &self,
        params: CloudRegistrationAzureDeleteLegacySubscriptionParams,
    ) -> Result<
        models::AzureLegacySubscriptionDeleteResponseExtV1,
        Error<CloudRegistrationAzureDeleteLegacySubscriptionError>,
    > {
        let CloudRegistrationAzureDeleteLegacySubscriptionParams { body } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/cloud-security-registration-azure/entities/accounts/legacy/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&body);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::AzureLegacySubscriptionDeleteResponseExtV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AzureLegacySubscriptionDeleteResponseExtV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<CloudRegistrationAzureDeleteLegacySubscriptionError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn cloud_registration_azure_delete_registration(
        &self,
        params: CloudRegistrationAzureDeleteRegistrationParams,
    ) -> Result<
        models::AzureDeleteRegistrationResponseExtV1,
        Error<CloudRegistrationAzureDeleteRegistrationError>,
    > {
        let CloudRegistrationAzureDeleteRegistrationParams { tenant_ids } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/cloud-security-registration-azure/entities/registrations/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        local_var_req_builder = match "multi" {
            "multi" => local_var_req_builder.query(
                &tenant_ids
                    .into_iter()
                    .map(|p| ("tenant_ids".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => local_var_req_builder.query(&[(
                "tenant_ids",
                &tenant_ids
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::AzureDeleteRegistrationResponseExtV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AzureDeleteRegistrationResponseExtV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<CloudRegistrationAzureDeleteRegistrationError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn cloud_registration_azure_download_script(
        &self,
        params: CloudRegistrationAzureDownloadScriptParams,
    ) -> Result<
        models::AzureAzureProvisionGetAccountScriptResponseV1,
        Error<CloudRegistrationAzureDownloadScriptError>,
    > {
        let CloudRegistrationAzureDownloadScriptParams { body } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/cloud-security-registration-azure/entities/scripts/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&body);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::AzureAzureProvisionGetAccountScriptResponseV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AzureAzureProvisionGetAccountScriptResponseV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<CloudRegistrationAzureDownloadScriptError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn cloud_registration_azure_get_registration(
        &self,
        params: CloudRegistrationAzureGetRegistrationParams,
    ) -> Result<
        models::AzureAzureRegistrationResponseExtV1,
        Error<CloudRegistrationAzureGetRegistrationError>,
    > {
        let CloudRegistrationAzureGetRegistrationParams { tenant_id } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/cloud-security-registration-azure/entities/registrations/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder =
            local_var_req_builder.query(&[("tenant_id", &tenant_id.to_string())]);
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::AzureAzureRegistrationResponseExtV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AzureAzureRegistrationResponseExtV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<CloudRegistrationAzureGetRegistrationError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn cloud_registration_azure_trigger_health_check(
        &self,
        params: CloudRegistrationAzureTriggerHealthCheckParams,
    ) -> Result<
        models::AzureHealthCheckTriggerResponseExtV1,
        Error<CloudRegistrationAzureTriggerHealthCheckError>,
    > {
        let CloudRegistrationAzureTriggerHealthCheckParams { tenant_ids } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/cloud-security-registration-azure/entities/registrations/healthcheck/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref param_value) = tenant_ids {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("tenant_ids".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "tenant_ids",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::AzureHealthCheckTriggerResponseExtV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AzureHealthCheckTriggerResponseExtV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<CloudRegistrationAzureTriggerHealthCheckError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn cloud_registration_azure_update_registration(
        &self,
        params: CloudRegistrationAzureUpdateRegistrationParams,
    ) -> Result<
        models::AzureAzureRegistrationResponseExtV1,
        Error<CloudRegistrationAzureUpdateRegistrationError>,
    > {
        let CloudRegistrationAzureUpdateRegistrationParams { body } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/cloud-security-registration-azure/entities/registrations/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PATCH, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&body);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::AzureAzureRegistrationResponseExtV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AzureAzureRegistrationResponseExtV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<CloudRegistrationAzureUpdateRegistrationError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn cloud_registration_azure_validate_registration(
        &self,
        params: CloudRegistrationAzureValidateRegistrationParams,
    ) -> Result<
        models::AzureRegistrationValidateResponseV1,
        Error<CloudRegistrationAzureValidateRegistrationError>,
    > {
        let CloudRegistrationAzureValidateRegistrationParams {
            tenant_id,
            stack_name,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/cloud-security-registration-azure/entities/registrations/validate/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder =
            local_var_req_builder.query(&[("tenant_id", &tenant_id.to_string())]);
        if let Some(ref param_value) = stack_name {
            local_var_req_builder =
                local_var_req_builder.query(&[("stack_name", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::AzureRegistrationValidateResponseV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AzureRegistrationValidateResponseV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<CloudRegistrationAzureValidateRegistrationError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn download_azure_script(
        &self,
        params: DownloadAzureScriptParams,
    ) -> Result<(), Error<DownloadAzureScriptError>> {
        let DownloadAzureScriptParams { tenant_id } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/cloud-security-registration-azure/entities/scripts/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder =
            local_var_req_builder.query(&[("tenant_id", &tenant_id.to_string())]);
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<DownloadAzureScriptError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`CloudAzureRegistrationApi::cloud_registration_azure_create_registration`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CloudRegistrationAzureCreateRegistrationError {
    Status400(models::MsaspecResponseFields),
    Status403(models::MsaspecResponseFields),
    Status409(models::MsaspecResponseFields),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::MsaspecResponseFields),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`CloudAzureRegistrationApi::cloud_registration_azure_delete_legacy_subscription`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CloudRegistrationAzureDeleteLegacySubscriptionError {
    Status400(models::MsaspecResponseFields),
    Status403(models::MsaspecResponseFields),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::MsaspecResponseFields),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`CloudAzureRegistrationApi::cloud_registration_azure_delete_registration`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CloudRegistrationAzureDeleteRegistrationError {
    Status400(models::MsaspecResponseFields),
    Status403(models::MsaspecResponseFields),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::MsaspecResponseFields),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`CloudAzureRegistrationApi::cloud_registration_azure_download_script`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CloudRegistrationAzureDownloadScriptError {
    Status400(models::MsaspecResponseFields),
    Status403(models::MsaspecResponseFields),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::MsaspecResponseFields),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`CloudAzureRegistrationApi::cloud_registration_azure_get_registration`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CloudRegistrationAzureGetRegistrationError {
    Status400(models::MsaspecResponseFields),
    Status403(models::MsaspecResponseFields),
    Status404(models::MsaspecResponseFields),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::MsaspecResponseFields),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`CloudAzureRegistrationApi::cloud_registration_azure_trigger_health_check`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CloudRegistrationAzureTriggerHealthCheckError {
    Status400(models::MsaspecResponseFields),
    Status403(models::MsaspecResponseFields),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::MsaspecResponseFields),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`CloudAzureRegistrationApi::cloud_registration_azure_update_registration`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CloudRegistrationAzureUpdateRegistrationError {
    Status400(models::MsaspecResponseFields),
    Status403(models::MsaspecResponseFields),
    Status404(models::MsaspecResponseFields),
    Status409(models::MsaspecResponseFields),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::MsaspecResponseFields),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`CloudAzureRegistrationApi::cloud_registration_azure_validate_registration`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CloudRegistrationAzureValidateRegistrationError {
    Status400(models::MsaspecResponseFields),
    Status403(models::MsaspecResponseFields),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::MsaspecResponseFields),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`CloudAzureRegistrationApi::download_azure_script`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DownloadAzureScriptError {
    Status400(models::MsaspecResponseFields),
    Status403(models::MsaReplyMetaOnly),
    Status404(models::MsaspecResponseFields),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::MsaspecResponseFields),
    UnknownValue(serde_json::Value),
}
