/*
 * CrowdStrike API Specification
 *
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: 2026-01-28T00:00:04Z
 *
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;

use async_trait::async_trait;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

use super::{Error, configuration};
use crate::experimental::{
    apis::{ContentType, ResponseContent},
    models,
};

#[async_trait]
pub trait CorrelationRulesAdminApi: Send + Sync {
    /// PUT /correlation-rules/entities/rules/ownership/v1
    ///
    ///
    async fn entities_rules_ownership_put_v1(
        &self,
        params: EntitiesRulesOwnershipPutV1Params,
    ) -> Result<
        models::CorrelationrulesapiGetEntitiesRulesResponseV1,
        Error<EntitiesRulesOwnershipPutV1Error>,
    >;
}

pub struct CorrelationRulesAdminApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl CorrelationRulesAdminApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

/// struct for passing parameters to the method [`CorrelationRulesAdminApi::entities_rules_ownership_put_v1`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct EntitiesRulesOwnershipPutV1Params {
    pub body: models::CorrelationrulesapiRuleOwnerPutRequestV1,
}

#[async_trait]
impl CorrelationRulesAdminApi for CorrelationRulesAdminApiClient {
    async fn entities_rules_ownership_put_v1(
        &self,
        params: EntitiesRulesOwnershipPutV1Params,
    ) -> Result<
        models::CorrelationrulesapiGetEntitiesRulesResponseV1,
        Error<EntitiesRulesOwnershipPutV1Error>,
    > {
        let EntitiesRulesOwnershipPutV1Params { body } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/correlation-rules/entities/rules/ownership/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&body);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::CorrelationrulesapiGetEntitiesRulesResponseV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::CorrelationrulesapiGetEntitiesRulesResponseV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<EntitiesRulesOwnershipPutV1Error> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`CorrelationRulesAdminApi::entities_rules_ownership_put_v1`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EntitiesRulesOwnershipPutV1Error {
    Status400(models::CorrelationrulesapiGetEntitiesRulesResponseV1),
    Status401(models::CorrelationrulesapiGetEntitiesRulesResponseV1),
    Status403(models::CorrelationrulesapiGetEntitiesRulesResponseV1),
    Status404(models::CorrelationrulesapiGetEntitiesRulesResponseV1),
    Status422(models::CorrelationrulesapiGetEntitiesRulesResponseV1),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::CorrelationrulesapiGetEntitiesRulesResponseV1),
    UnknownValue(serde_json::Value),
}
