/*
 * CrowdStrike API Specification
 *
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: 2026-01-28T00:00:04Z
 *
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;

use async_trait::async_trait;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

use super::{Error, configuration};
use crate::experimental::{
    apis::{ContentType, ResponseContent},
    models,
};

#[async_trait]
pub trait HostGroupApi: Send + Sync {
    /// POST /devices/entities/host-groups/v1
    ///
    ///
    async fn create_host_groups(
        &self,
        params: CreateHostGroupsParams,
    ) -> Result<models::HostGroupsRespV1, Error<CreateHostGroupsError>>;

    /// DELETE /devices/entities/host-groups/v1
    ///
    ///
    async fn delete_host_groups(
        &self,
        params: DeleteHostGroupsParams,
    ) -> Result<models::MsaQueryResponse, Error<DeleteHostGroupsError>>;

    /// GET /devices/entities/host-groups/v1
    ///
    ///
    async fn get_host_groups(
        &self,
        params: GetHostGroupsParams,
    ) -> Result<models::HostGroupsRespV1, Error<GetHostGroupsError>>;

    /// POST /devices/entities/host-group-actions/v1
    ///
    ///
    async fn perform_group_action(
        &self,
        params: PerformGroupActionParams,
    ) -> Result<models::HostGroupsRespV1, Error<PerformGroupActionError>>;

    /// GET /devices/combined/host-group-members/v1
    ///
    ///
    async fn query_combined_group_members(
        &self,
        params: QueryCombinedGroupMembersParams,
    ) -> Result<models::HostGroupsMembersRespV1, Error<QueryCombinedGroupMembersError>>;

    /// GET /devices/combined/host-groups/v1
    ///
    ///
    async fn query_combined_host_groups(
        &self,
        params: QueryCombinedHostGroupsParams,
    ) -> Result<models::HostGroupsRespV1, Error<QueryCombinedHostGroupsError>>;

    /// GET /devices/queries/host-group-members/v1
    ///
    ///
    async fn query_group_members(
        &self,
        params: QueryGroupMembersParams,
    ) -> Result<models::MsaQueryResponse, Error<QueryGroupMembersError>>;

    /// GET /devices/queries/host-groups/v1
    ///
    ///
    async fn query_host_groups(
        &self,
        params: QueryHostGroupsParams,
    ) -> Result<models::MsaQueryResponse, Error<QueryHostGroupsError>>;

    /// PATCH /devices/entities/host-groups/v1
    ///
    ///
    async fn update_host_groups(
        &self,
        params: UpdateHostGroupsParams,
    ) -> Result<models::HostGroupsRespV1, Error<UpdateHostGroupsError>>;
}

pub struct HostGroupApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl HostGroupApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

/// struct for passing parameters to the method [`HostGroupApi::create_host_groups`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct CreateHostGroupsParams {
    pub body: models::HostGroupsCreateGroupsReqV1,
}

/// struct for passing parameters to the method [`HostGroupApi::delete_host_groups`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct DeleteHostGroupsParams {
    /// The IDs of the Host Groups to delete
    pub ids: Vec<String>,
}

/// struct for passing parameters to the method [`HostGroupApi::get_host_groups`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct GetHostGroupsParams {
    /// The IDs of the Host Groups to return
    pub ids: Vec<String>,
}

/// struct for passing parameters to the method [`HostGroupApi::perform_group_action`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct PerformGroupActionParams {
    /// The action to perform
    pub action_name: String,
    pub body: models::MsaEntityActionRequestV2,
    /// Bool to disable hostname check on add-member
    pub disable_hostname_check: Option<bool>,
}

/// struct for passing parameters to the method [`HostGroupApi::query_combined_group_members`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct QueryCombinedGroupMembersParams {
    /// The ID of the Host Group to search for members of
    pub id: Option<String>,
    /// The filter expression that should be used to limit the results
    pub filter: Option<String>,
    /// The offset to start retrieving records from
    pub offset: Option<u32>,
    /// The maximum records to return. [1-5000]
    pub limit: Option<u16>,
    /// The property to sort by
    pub sort: Option<String>,
}

/// struct for passing parameters to the method [`HostGroupApi::query_combined_host_groups`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct QueryCombinedHostGroupsParams {
    /// The filter expression that should be used to limit the results
    pub filter: Option<String>,
    /// The offset to start retrieving records from
    pub offset: Option<u32>,
    /// The maximum records to return. [1-5000]
    pub limit: Option<u16>,
    /// The property to sort by
    pub sort: Option<String>,
}

/// struct for passing parameters to the method [`HostGroupApi::query_group_members`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct QueryGroupMembersParams {
    /// The ID of the Host Group to search for members of
    pub id: Option<String>,
    /// The filter expression that should be used to limit the results
    pub filter: Option<String>,
    /// The offset to start retrieving records from
    pub offset: Option<u32>,
    /// The maximum records to return. [1-5000]
    pub limit: Option<u16>,
    /// The property to sort by
    pub sort: Option<String>,
}

/// struct for passing parameters to the method [`HostGroupApi::query_host_groups`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct QueryHostGroupsParams {
    /// The filter expression that should be used to limit the results
    pub filter: Option<String>,
    /// The offset to start retrieving records from
    pub offset: Option<u32>,
    /// The maximum records to return. [1-5000]
    pub limit: Option<u16>,
    /// The property to sort by
    pub sort: Option<String>,
}

/// struct for passing parameters to the method [`HostGroupApi::update_host_groups`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct UpdateHostGroupsParams {
    pub body: models::HostGroupsUpdateGroupsReqV1,
}

#[async_trait]
impl HostGroupApi for HostGroupApiClient {
    async fn create_host_groups(
        &self,
        params: CreateHostGroupsParams,
    ) -> Result<models::HostGroupsRespV1, Error<CreateHostGroupsError>> {
        let CreateHostGroupsParams { body } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/devices/entities/host-groups/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&body);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::HostGroupsRespV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::HostGroupsRespV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<CreateHostGroupsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn delete_host_groups(
        &self,
        params: DeleteHostGroupsParams,
    ) -> Result<models::MsaQueryResponse, Error<DeleteHostGroupsError>> {
        let DeleteHostGroupsParams { ids } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/devices/entities/host-groups/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        local_var_req_builder = match "multi" {
            "multi" => local_var_req_builder.query(
                &ids.into_iter()
                    .map(|p| ("ids".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => local_var_req_builder.query(&[(
                "ids",
                &ids.into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::MsaQueryResponse`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::MsaQueryResponse`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<DeleteHostGroupsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn get_host_groups(
        &self,
        params: GetHostGroupsParams,
    ) -> Result<models::HostGroupsRespV1, Error<GetHostGroupsError>> {
        let GetHostGroupsParams { ids } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/devices/entities/host-groups/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = match "multi" {
            "multi" => local_var_req_builder.query(
                &ids.into_iter()
                    .map(|p| ("ids".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => local_var_req_builder.query(&[(
                "ids",
                &ids.into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::HostGroupsRespV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::HostGroupsRespV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<GetHostGroupsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn perform_group_action(
        &self,
        params: PerformGroupActionParams,
    ) -> Result<models::HostGroupsRespV1, Error<PerformGroupActionError>> {
        let PerformGroupActionParams {
            action_name,
            body,
            disable_hostname_check,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/devices/entities/host-group-actions/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder =
            local_var_req_builder.query(&[("action_name", &action_name.to_string())]);
        if let Some(ref param_value) = disable_hostname_check {
            local_var_req_builder = local_var_req_builder
                .query(&[("disable_hostname_check", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&body);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::HostGroupsRespV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::HostGroupsRespV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<PerformGroupActionError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn query_combined_group_members(
        &self,
        params: QueryCombinedGroupMembersParams,
    ) -> Result<models::HostGroupsMembersRespV1, Error<QueryCombinedGroupMembersError>> {
        let QueryCombinedGroupMembersParams {
            id,
            filter,
            offset,
            limit,
            sort,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/devices/combined/host-group-members/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = id {
            local_var_req_builder =
                local_var_req_builder.query(&[("id", &param_value.to_string())]);
        }
        if let Some(ref param_value) = filter {
            local_var_req_builder =
                local_var_req_builder.query(&[("filter", &param_value.to_string())]);
        }
        if let Some(ref param_value) = offset {
            local_var_req_builder =
                local_var_req_builder.query(&[("offset", &param_value.to_string())]);
        }
        if let Some(ref param_value) = limit {
            local_var_req_builder =
                local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = sort {
            local_var_req_builder =
                local_var_req_builder.query(&[("sort", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::HostGroupsMembersRespV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::HostGroupsMembersRespV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<QueryCombinedGroupMembersError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn query_combined_host_groups(
        &self,
        params: QueryCombinedHostGroupsParams,
    ) -> Result<models::HostGroupsRespV1, Error<QueryCombinedHostGroupsError>> {
        let QueryCombinedHostGroupsParams {
            filter,
            offset,
            limit,
            sort,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/devices/combined/host-groups/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = filter {
            local_var_req_builder =
                local_var_req_builder.query(&[("filter", &param_value.to_string())]);
        }
        if let Some(ref param_value) = offset {
            local_var_req_builder =
                local_var_req_builder.query(&[("offset", &param_value.to_string())]);
        }
        if let Some(ref param_value) = limit {
            local_var_req_builder =
                local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = sort {
            local_var_req_builder =
                local_var_req_builder.query(&[("sort", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::HostGroupsRespV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::HostGroupsRespV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<QueryCombinedHostGroupsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn query_group_members(
        &self,
        params: QueryGroupMembersParams,
    ) -> Result<models::MsaQueryResponse, Error<QueryGroupMembersError>> {
        let QueryGroupMembersParams {
            id,
            filter,
            offset,
            limit,
            sort,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/devices/queries/host-group-members/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = id {
            local_var_req_builder =
                local_var_req_builder.query(&[("id", &param_value.to_string())]);
        }
        if let Some(ref param_value) = filter {
            local_var_req_builder =
                local_var_req_builder.query(&[("filter", &param_value.to_string())]);
        }
        if let Some(ref param_value) = offset {
            local_var_req_builder =
                local_var_req_builder.query(&[("offset", &param_value.to_string())]);
        }
        if let Some(ref param_value) = limit {
            local_var_req_builder =
                local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = sort {
            local_var_req_builder =
                local_var_req_builder.query(&[("sort", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::MsaQueryResponse`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::MsaQueryResponse`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<QueryGroupMembersError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn query_host_groups(
        &self,
        params: QueryHostGroupsParams,
    ) -> Result<models::MsaQueryResponse, Error<QueryHostGroupsError>> {
        let QueryHostGroupsParams {
            filter,
            offset,
            limit,
            sort,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/devices/queries/host-groups/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = filter {
            local_var_req_builder =
                local_var_req_builder.query(&[("filter", &param_value.to_string())]);
        }
        if let Some(ref param_value) = offset {
            local_var_req_builder =
                local_var_req_builder.query(&[("offset", &param_value.to_string())]);
        }
        if let Some(ref param_value) = limit {
            local_var_req_builder =
                local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = sort {
            local_var_req_builder =
                local_var_req_builder.query(&[("sort", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::MsaQueryResponse`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::MsaQueryResponse`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<QueryHostGroupsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn update_host_groups(
        &self,
        params: UpdateHostGroupsParams,
    ) -> Result<models::HostGroupsRespV1, Error<UpdateHostGroupsError>> {
        let UpdateHostGroupsParams { body } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/devices/entities/host-groups/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PATCH, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&body);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::HostGroupsRespV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::HostGroupsRespV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<UpdateHostGroupsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`HostGroupApi::create_host_groups`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateHostGroupsError {
    Status400(models::HostGroupsRespV1),
    Status403(models::MsaReplyMetaOnly),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::HostGroupsRespV1),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`HostGroupApi::delete_host_groups`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteHostGroupsError {
    Status403(models::MsaReplyMetaOnly),
    Status404(models::MsaQueryResponse),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::MsaQueryResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`HostGroupApi::get_host_groups`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetHostGroupsError {
    Status400(models::HostGroupsRespV1),
    Status403(models::MsaErrorsOnly),
    Status404(models::HostGroupsRespV1),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::HostGroupsRespV1),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`HostGroupApi::perform_group_action`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PerformGroupActionError {
    Status400(models::HostGroupsRespV1),
    Status403(models::MsaErrorsOnly),
    Status404(models::HostGroupsRespV1),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::HostGroupsRespV1),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`HostGroupApi::query_combined_group_members`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QueryCombinedGroupMembersError {
    Status400(models::HostGroupsMembersRespV1),
    Status403(models::MsaErrorsOnly),
    Status404(models::HostGroupsMembersRespV1),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::HostGroupsMembersRespV1),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`HostGroupApi::query_combined_host_groups`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QueryCombinedHostGroupsError {
    Status400(models::HostGroupsRespV1),
    Status403(models::MsaErrorsOnly),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::HostGroupsRespV1),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`HostGroupApi::query_group_members`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QueryGroupMembersError {
    Status400(models::MsaQueryResponse),
    Status403(models::MsaErrorsOnly),
    Status404(models::MsaQueryResponse),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::MsaQueryResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`HostGroupApi::query_host_groups`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QueryHostGroupsError {
    Status400(models::MsaQueryResponse),
    Status403(models::MsaErrorsOnly),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::MsaQueryResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`HostGroupApi::update_host_groups`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateHostGroupsError {
    Status400(models::HostGroupsRespV1),
    Status403(models::MsaErrorsOnly),
    Status404(models::HostGroupsRespV1),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::HostGroupsRespV1),
    UnknownValue(serde_json::Value),
}
