/*
 * CrowdStrike API Specification
 *
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: 2026-01-28T00:00:04Z
 *
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;

use async_trait::async_trait;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

use super::{Error, configuration};
use crate::experimental::{
    apis::{ContentType, ResponseContent},
    models,
};

#[async_trait]
pub trait LookupFilesApi: Send + Sync {
    /// POST /loggingapi/entities/lookup-files/v1
    ///
    ///
    async fn create_file_v1(
        &self,
        params: CreateFileV1Params,
    ) -> Result<models::DomainLookupFileWrapper, Error<CreateFileV1Error>>;

    /// PATCH /loggingapi/entities/lookup-files/v1
    ///
    ///
    async fn update_file_v1(
        &self,
        params: UpdateFileV1Params,
    ) -> Result<models::DomainLookupFileWrapper, Error<UpdateFileV1Error>>;
}

pub struct LookupFilesApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl LookupFilesApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

/// struct for passing parameters to the method [`LookupFilesApi::create_file_v1`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct CreateFileV1Params {
    /// File to be uploaded
    pub file: std::path::PathBuf,
    /// Name used to identify the file
    pub name: String,
    /// Requester Username.
    pub x_cs_username: Option<String>,
    /// Requester UUID.
    pub x_cs_useruuid: Option<String>,
    /// File description
    pub description: Option<String>,
    /// Unique identifier of the file being updated.
    pub id: Option<String>,
    /// Name of repository or view to save the file
    pub repo: Option<String>,
}

/// struct for passing parameters to the method [`LookupFilesApi::update_file_v1`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct UpdateFileV1Params {
    /// Unique identifier of the file being updated.
    pub id: String,
    /// Requester Username.
    pub x_cs_username: Option<String>,
    /// Requester UUID.
    pub x_cs_useruuid: Option<String>,
    /// File description
    pub description: Option<String>,
    /// File to be uploaded
    pub file: Option<std::path::PathBuf>,
}

#[async_trait]
impl LookupFilesApi for LookupFilesApiClient {
    async fn create_file_v1(
        &self,
        params: CreateFileV1Params,
    ) -> Result<models::DomainLookupFileWrapper, Error<CreateFileV1Error>> {
        let CreateFileV1Params {
            file,
            name,
            x_cs_username,
            x_cs_useruuid,
            description,
            id,
            repo,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/loggingapi/entities/lookup-files/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = x_cs_username {
            local_var_req_builder =
                local_var_req_builder.header("X-CS-USERNAME", local_var_param_value.to_string());
        }
        if let Some(local_var_param_value) = x_cs_useruuid {
            local_var_req_builder =
                local_var_req_builder.header("X-CS-USERUUID", local_var_param_value.to_string());
        }
        let mut local_var_form = reqwest::multipart::Form::new();
        {
            let path = &file;
            local_var_form = local_var_form.file("file", path.as_os_str()).await?;
        }
        local_var_form = local_var_form.text("name", name.to_string());
        if let Some(local_var_param_value) = description {
            local_var_form = local_var_form.text("description", local_var_param_value.to_string());
        }
        if let Some(local_var_param_value) = id {
            local_var_form = local_var_form.text("id", local_var_param_value.to_string());
        }
        if let Some(local_var_param_value) = repo {
            local_var_form = local_var_form.text("repo", local_var_param_value.to_string());
        }
        local_var_req_builder = local_var_req_builder.multipart(local_var_form);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::DomainLookupFileWrapper`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::DomainLookupFileWrapper`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<CreateFileV1Error> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn update_file_v1(
        &self,
        params: UpdateFileV1Params,
    ) -> Result<models::DomainLookupFileWrapper, Error<UpdateFileV1Error>> {
        let UpdateFileV1Params {
            id,
            x_cs_username,
            x_cs_useruuid,
            description,
            file,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/loggingapi/entities/lookup-files/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PATCH, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(local_var_param_value) = x_cs_username {
            local_var_req_builder =
                local_var_req_builder.header("X-CS-USERNAME", local_var_param_value.to_string());
        }
        if let Some(local_var_param_value) = x_cs_useruuid {
            local_var_req_builder =
                local_var_req_builder.header("X-CS-USERUUID", local_var_param_value.to_string());
        }
        let mut local_var_form = reqwest::multipart::Form::new();
        local_var_form = local_var_form.text("id", id.to_string());
        if let Some(local_var_param_value) = description {
            local_var_form = local_var_form.text("description", local_var_param_value.to_string());
        }
        if let Some(ref path) = file {
            local_var_form = local_var_form.file("file", path.as_os_str()).await?;
        }
        local_var_req_builder = local_var_req_builder.multipart(local_var_form);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::DomainLookupFileWrapper`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::DomainLookupFileWrapper`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<UpdateFileV1Error> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`LookupFilesApi::create_file_v1`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateFileV1Error {
    Status400(models::MsaspecResponseFields),
    Status403(models::MsaspecResponseFields),
    Status404(models::MsaspecResponseFields),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::MsaspecResponseFields),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`LookupFilesApi::update_file_v1`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateFileV1Error {
    Status400(models::MsaspecResponseFields),
    Status403(models::MsaspecResponseFields),
    Status404(models::MsaspecResponseFields),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::MsaspecResponseFields),
    UnknownValue(serde_json::Value),
}
