/*
 * CrowdStrike API Specification
 *
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: 2026-01-28T00:00:04Z
 *
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;

use async_trait::async_trait;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

use super::{Error, configuration};
use crate::experimental::{
    apis::{ContentType, ResponseContent},
    models,
};

#[async_trait]
pub trait PreventionPoliciesApi: Send + Sync {
    /// POST /policy/entities/prevention/v1
    ///
    ///
    async fn create_prevention_policies(
        &self,
        params: CreatePreventionPoliciesParams,
    ) -> Result<models::PreventionRespV1, Error<CreatePreventionPoliciesError>>;

    /// DELETE /policy/entities/prevention/v1
    ///
    ///
    async fn delete_prevention_policies(
        &self,
        params: DeletePreventionPoliciesParams,
    ) -> Result<models::MsaQueryResponse, Error<DeletePreventionPoliciesError>>;

    /// GET /policy/entities/prevention/v1
    ///
    ///
    async fn get_prevention_policies(
        &self,
        params: GetPreventionPoliciesParams,
    ) -> Result<models::PreventionRespV1, Error<GetPreventionPoliciesError>>;

    /// POST /policy/entities/prevention-actions/v1
    ///
    ///
    async fn perform_prevention_policies_action(
        &self,
        params: PerformPreventionPoliciesActionParams,
    ) -> Result<models::PreventionRespV1, Error<PerformPreventionPoliciesActionError>>;

    /// GET /policy/combined/prevention/v1
    ///
    ///
    async fn query_combined_prevention_policies(
        &self,
        params: QueryCombinedPreventionPoliciesParams,
    ) -> Result<models::PreventionRespV1, Error<QueryCombinedPreventionPoliciesError>>;

    /// GET /policy/combined/prevention-members/v1
    ///
    ///
    async fn query_combined_prevention_policy_members(
        &self,
        params: QueryCombinedPreventionPolicyMembersParams,
    ) -> Result<models::BasePolicyMembersRespV1, Error<QueryCombinedPreventionPolicyMembersError>>;

    /// GET /policy/queries/prevention/v1
    ///
    ///
    async fn query_prevention_policies(
        &self,
        params: QueryPreventionPoliciesParams,
    ) -> Result<models::MsaQueryResponse, Error<QueryPreventionPoliciesError>>;

    /// GET /policy/queries/prevention-members/v1
    ///
    ///
    async fn query_prevention_policy_members(
        &self,
        params: QueryPreventionPolicyMembersParams,
    ) -> Result<models::MsaQueryResponse, Error<QueryPreventionPolicyMembersError>>;

    /// POST /policy/entities/prevention-precedence/v1
    ///
    ///
    async fn set_prevention_policies_precedence(
        &self,
        params: SetPreventionPoliciesPrecedenceParams,
    ) -> Result<models::MsaQueryResponse, Error<SetPreventionPoliciesPrecedenceError>>;

    /// PATCH /policy/entities/prevention/v1
    ///
    ///
    async fn update_prevention_policies(
        &self,
        params: UpdatePreventionPoliciesParams,
    ) -> Result<models::PreventionRespV1, Error<UpdatePreventionPoliciesError>>;
}

pub struct PreventionPoliciesApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl PreventionPoliciesApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

/// struct for passing parameters to the method [`PreventionPoliciesApi::create_prevention_policies`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct CreatePreventionPoliciesParams {
    pub body: models::PreventionCreatePoliciesReqV1,
}

/// struct for passing parameters to the method [`PreventionPoliciesApi::delete_prevention_policies`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct DeletePreventionPoliciesParams {
    /// The IDs of the Prevention Policies to delete
    pub ids: Vec<String>,
}

/// struct for passing parameters to the method [`PreventionPoliciesApi::get_prevention_policies`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct GetPreventionPoliciesParams {
    /// The IDs of the Prevention Policies to return
    pub ids: Vec<String>,
}

/// struct for passing parameters to the method [`PreventionPoliciesApi::perform_prevention_policies_action`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct PerformPreventionPoliciesActionParams {
    /// The action to perform
    pub action_name: String,
    pub body: models::MsaEntityActionRequestV2,
}

/// struct for passing parameters to the method [`PreventionPoliciesApi::query_combined_prevention_policies`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct QueryCombinedPreventionPoliciesParams {
    /// The filter expression that should be used to limit the results
    pub filter: Option<String>,
    /// The offset to start retrieving records from
    pub offset: Option<u32>,
    /// The maximum records to return. [1-5000]
    pub limit: Option<u16>,
    /// The property to sort by
    pub sort: Option<String>,
}

/// struct for passing parameters to the method [`PreventionPoliciesApi::query_combined_prevention_policy_members`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct QueryCombinedPreventionPolicyMembersParams {
    /// The ID of the Prevention Policy to search for members of
    pub id: Option<String>,
    /// The filter expression that should be used to limit the results
    pub filter: Option<String>,
    /// The offset to start retrieving records from
    pub offset: Option<u32>,
    /// The maximum records to return. [1-5000]
    pub limit: Option<u16>,
    /// The property to sort by
    pub sort: Option<String>,
}

/// struct for passing parameters to the method [`PreventionPoliciesApi::query_prevention_policies`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct QueryPreventionPoliciesParams {
    /// The filter expression that should be used to limit the results
    pub filter: Option<String>,
    /// The offset to start retrieving records from
    pub offset: Option<u32>,
    /// The maximum records to return. [1-5000]
    pub limit: Option<u16>,
    /// The property to sort by
    pub sort: Option<String>,
}

/// struct for passing parameters to the method [`PreventionPoliciesApi::query_prevention_policy_members`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct QueryPreventionPolicyMembersParams {
    /// The ID of the Prevention Policy to search for members of
    pub id: Option<String>,
    /// The filter expression that should be used to limit the results
    pub filter: Option<String>,
    /// The offset to start retrieving records from
    pub offset: Option<u32>,
    /// The maximum records to return. [1-5000]
    pub limit: Option<u16>,
    /// The property to sort by
    pub sort: Option<String>,
}

/// struct for passing parameters to the method [`PreventionPoliciesApi::set_prevention_policies_precedence`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct SetPreventionPoliciesPrecedenceParams {
    pub body: models::BaseSetPolicyPrecedenceReqV1,
}

/// struct for passing parameters to the method [`PreventionPoliciesApi::update_prevention_policies`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct UpdatePreventionPoliciesParams {
    pub body: models::PreventionUpdatePoliciesReqV1,
}

#[async_trait]
impl PreventionPoliciesApi for PreventionPoliciesApiClient {
    async fn create_prevention_policies(
        &self,
        params: CreatePreventionPoliciesParams,
    ) -> Result<models::PreventionRespV1, Error<CreatePreventionPoliciesError>> {
        let CreatePreventionPoliciesParams { body } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/policy/entities/prevention/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&body);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::PreventionRespV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::PreventionRespV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<CreatePreventionPoliciesError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn delete_prevention_policies(
        &self,
        params: DeletePreventionPoliciesParams,
    ) -> Result<models::MsaQueryResponse, Error<DeletePreventionPoliciesError>> {
        let DeletePreventionPoliciesParams { ids } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/policy/entities/prevention/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        local_var_req_builder = match "multi" {
            "multi" => local_var_req_builder.query(
                &ids.into_iter()
                    .map(|p| ("ids".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => local_var_req_builder.query(&[(
                "ids",
                &ids.into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::MsaQueryResponse`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::MsaQueryResponse`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<DeletePreventionPoliciesError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn get_prevention_policies(
        &self,
        params: GetPreventionPoliciesParams,
    ) -> Result<models::PreventionRespV1, Error<GetPreventionPoliciesError>> {
        let GetPreventionPoliciesParams { ids } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/policy/entities/prevention/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = match "multi" {
            "multi" => local_var_req_builder.query(
                &ids.into_iter()
                    .map(|p| ("ids".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => local_var_req_builder.query(&[(
                "ids",
                &ids.into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::PreventionRespV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::PreventionRespV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<GetPreventionPoliciesError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn perform_prevention_policies_action(
        &self,
        params: PerformPreventionPoliciesActionParams,
    ) -> Result<models::PreventionRespV1, Error<PerformPreventionPoliciesActionError>> {
        let PerformPreventionPoliciesActionParams { action_name, body } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/policy/entities/prevention-actions/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder =
            local_var_req_builder.query(&[("action_name", &action_name.to_string())]);
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&body);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::PreventionRespV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::PreventionRespV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<PerformPreventionPoliciesActionError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn query_combined_prevention_policies(
        &self,
        params: QueryCombinedPreventionPoliciesParams,
    ) -> Result<models::PreventionRespV1, Error<QueryCombinedPreventionPoliciesError>> {
        let QueryCombinedPreventionPoliciesParams {
            filter,
            offset,
            limit,
            sort,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/policy/combined/prevention/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = filter {
            local_var_req_builder =
                local_var_req_builder.query(&[("filter", &param_value.to_string())]);
        }
        if let Some(ref param_value) = offset {
            local_var_req_builder =
                local_var_req_builder.query(&[("offset", &param_value.to_string())]);
        }
        if let Some(ref param_value) = limit {
            local_var_req_builder =
                local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = sort {
            local_var_req_builder =
                local_var_req_builder.query(&[("sort", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::PreventionRespV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::PreventionRespV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<QueryCombinedPreventionPoliciesError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn query_combined_prevention_policy_members(
        &self,
        params: QueryCombinedPreventionPolicyMembersParams,
    ) -> Result<models::BasePolicyMembersRespV1, Error<QueryCombinedPreventionPolicyMembersError>>
    {
        let QueryCombinedPreventionPolicyMembersParams {
            id,
            filter,
            offset,
            limit,
            sort,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/policy/combined/prevention-members/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = id {
            local_var_req_builder =
                local_var_req_builder.query(&[("id", &param_value.to_string())]);
        }
        if let Some(ref param_value) = filter {
            local_var_req_builder =
                local_var_req_builder.query(&[("filter", &param_value.to_string())]);
        }
        if let Some(ref param_value) = offset {
            local_var_req_builder =
                local_var_req_builder.query(&[("offset", &param_value.to_string())]);
        }
        if let Some(ref param_value) = limit {
            local_var_req_builder =
                local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = sort {
            local_var_req_builder =
                local_var_req_builder.query(&[("sort", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::BasePolicyMembersRespV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::BasePolicyMembersRespV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<QueryCombinedPreventionPolicyMembersError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn query_prevention_policies(
        &self,
        params: QueryPreventionPoliciesParams,
    ) -> Result<models::MsaQueryResponse, Error<QueryPreventionPoliciesError>> {
        let QueryPreventionPoliciesParams {
            filter,
            offset,
            limit,
            sort,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/policy/queries/prevention/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = filter {
            local_var_req_builder =
                local_var_req_builder.query(&[("filter", &param_value.to_string())]);
        }
        if let Some(ref param_value) = offset {
            local_var_req_builder =
                local_var_req_builder.query(&[("offset", &param_value.to_string())]);
        }
        if let Some(ref param_value) = limit {
            local_var_req_builder =
                local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = sort {
            local_var_req_builder =
                local_var_req_builder.query(&[("sort", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::MsaQueryResponse`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::MsaQueryResponse`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<QueryPreventionPoliciesError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn query_prevention_policy_members(
        &self,
        params: QueryPreventionPolicyMembersParams,
    ) -> Result<models::MsaQueryResponse, Error<QueryPreventionPolicyMembersError>> {
        let QueryPreventionPolicyMembersParams {
            id,
            filter,
            offset,
            limit,
            sort,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/policy/queries/prevention-members/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = id {
            local_var_req_builder =
                local_var_req_builder.query(&[("id", &param_value.to_string())]);
        }
        if let Some(ref param_value) = filter {
            local_var_req_builder =
                local_var_req_builder.query(&[("filter", &param_value.to_string())]);
        }
        if let Some(ref param_value) = offset {
            local_var_req_builder =
                local_var_req_builder.query(&[("offset", &param_value.to_string())]);
        }
        if let Some(ref param_value) = limit {
            local_var_req_builder =
                local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = sort {
            local_var_req_builder =
                local_var_req_builder.query(&[("sort", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::MsaQueryResponse`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::MsaQueryResponse`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<QueryPreventionPolicyMembersError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn set_prevention_policies_precedence(
        &self,
        params: SetPreventionPoliciesPrecedenceParams,
    ) -> Result<models::MsaQueryResponse, Error<SetPreventionPoliciesPrecedenceError>> {
        let SetPreventionPoliciesPrecedenceParams { body } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/policy/entities/prevention-precedence/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&body);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::MsaQueryResponse`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::MsaQueryResponse`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<SetPreventionPoliciesPrecedenceError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn update_prevention_policies(
        &self,
        params: UpdatePreventionPoliciesParams,
    ) -> Result<models::PreventionRespV1, Error<UpdatePreventionPoliciesError>> {
        let UpdatePreventionPoliciesParams { body } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/policy/entities/prevention/v1",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PATCH, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&body);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::PreventionRespV1`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::PreventionRespV1`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<UpdatePreventionPoliciesError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`PreventionPoliciesApi::create_prevention_policies`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreatePreventionPoliciesError {
    Status400(models::PreventionRespV1),
    Status403(models::MsaErrorsOnly),
    Status404(models::PreventionRespV1),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::PreventionRespV1),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`PreventionPoliciesApi::delete_prevention_policies`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeletePreventionPoliciesError {
    Status403(models::MsaErrorsOnly),
    Status404(models::MsaQueryResponse),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::MsaQueryResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`PreventionPoliciesApi::get_prevention_policies`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetPreventionPoliciesError {
    Status403(models::MsaErrorsOnly),
    Status404(models::PreventionRespV1),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::PreventionRespV1),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`PreventionPoliciesApi::perform_prevention_policies_action`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PerformPreventionPoliciesActionError {
    Status400(models::PreventionRespV1),
    Status403(models::MsaErrorsOnly),
    Status404(models::PreventionRespV1),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::PreventionRespV1),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`PreventionPoliciesApi::query_combined_prevention_policies`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QueryCombinedPreventionPoliciesError {
    Status400(models::PreventionRespV1),
    Status403(models::MsaErrorsOnly),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::PreventionRespV1),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`PreventionPoliciesApi::query_combined_prevention_policy_members`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QueryCombinedPreventionPolicyMembersError {
    Status400(models::BasePolicyMembersRespV1),
    Status403(models::MsaErrorsOnly),
    Status404(models::BasePolicyMembersRespV1),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::BasePolicyMembersRespV1),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`PreventionPoliciesApi::query_prevention_policies`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QueryPreventionPoliciesError {
    Status400(models::MsaQueryResponse),
    Status403(models::MsaErrorsOnly),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::MsaQueryResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`PreventionPoliciesApi::query_prevention_policy_members`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QueryPreventionPolicyMembersError {
    Status400(models::MsaQueryResponse),
    Status403(models::MsaErrorsOnly),
    Status404(models::MsaQueryResponse),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::MsaQueryResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`PreventionPoliciesApi::set_prevention_policies_precedence`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SetPreventionPoliciesPrecedenceError {
    Status400(models::MsaQueryResponse),
    Status403(models::MsaErrorsOnly),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::MsaQueryResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`PreventionPoliciesApi::update_prevention_policies`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdatePreventionPoliciesError {
    Status400(models::PreventionRespV1),
    Status403(models::MsaErrorsOnly),
    Status404(models::PreventionRespV1),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::PreventionRespV1),
    UnknownValue(serde_json::Value),
}
