/*
 * CrowdStrike API Specification
 *
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: 2026-01-28T00:00:04Z
 *
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;

use async_trait::async_trait;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

use super::{Error, configuration};
use crate::experimental::{
    apis::{ContentType, ResponseContent},
    models,
};

#[async_trait]
pub trait TailoredIntelligenceApi: Send + Sync {
    /// GET /ti/events/entities/events-full-body/v2
    ///
    ///
    async fn get_events_body(
        &self,
        params: GetEventsBodyParams,
    ) -> Result<Vec<i32>, Error<GetEventsBodyError>>;

    /// POST /ti/events/entities/events/GET/v2
    ///
    ///
    async fn get_events_entities(
        &self,
        params: GetEventsEntitiesParams,
    ) -> Result<models::DomainEventEntitiesResponse, Error<GetEventsEntitiesError>>;

    /// POST /ti/rules/entities/rules/GET/v2
    ///
    ///
    async fn get_rules_entities(
        &self,
        params: GetRulesEntitiesParams,
    ) -> Result<models::DomainRuleEntitiesResponse, Error<GetRulesEntitiesError>>;

    /// GET /ti/events/queries/events/v2
    ///
    ///
    async fn query_events(
        &self,
        params: QueryEventsParams,
    ) -> Result<models::DomainQueryResponse, Error<QueryEventsError>>;

    /// GET /ti/rules/queries/rules/v2
    ///
    ///
    async fn query_rules(
        &self,
        params: QueryRulesParams,
    ) -> Result<models::DomainQueryResponse, Error<QueryRulesError>>;
}

pub struct TailoredIntelligenceApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl TailoredIntelligenceApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

/// struct for passing parameters to the method [`TailoredIntelligenceApi::get_events_body`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct GetEventsBodyParams {
    /// Return the event body for event id.
    pub id: String,
}

/// struct for passing parameters to the method [`TailoredIntelligenceApi::get_events_entities`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct GetEventsEntitiesParams {
    pub body: models::MsaIdsRequest,
}

/// struct for passing parameters to the method [`TailoredIntelligenceApi::get_rules_entities`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct GetRulesEntitiesParams {
    pub body: models::MsaIdsRequest,
}

/// struct for passing parameters to the method [`TailoredIntelligenceApi::query_events`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct QueryEventsParams {
    /// Starting index of overall result set from which to return ids.
    pub offset: Option<String>,
    /// Number of ids to return.
    pub limit: Option<i32>,
    /// Possible order by fields: source_type, created_date, updated_date. Ex: 'updated_date|desc'.
    pub sort: Option<String>,
    /// FQL query specifying the filter parameters. Special value '*' means to not filter on anything.
    pub filter: Option<String>,
    /// Match phrase_prefix query criteria; included fields: _all (all filter string fields indexed).
    pub q: Option<String>,
}

/// struct for passing parameters to the method [`TailoredIntelligenceApi::query_rules`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct QueryRulesParams {
    /// Starting index of overall result set from which to return ids.
    pub offset: Option<String>,
    /// Number of ids to return.
    pub limit: Option<i32>,
    /// Possible order by fields: name, value, rule_type, customer_id, created_date, updated_date. Ex: 'updated_date|asc'.
    pub sort: Option<String>,
    /// FQL query specifying the filter parameters. Special value '*' means to not filter on anything.
    pub filter: Option<String>,
    /// Match phrase_prefix query criteria; included fields: _all (all filter string fields indexed).
    pub q: Option<String>,
}

#[async_trait]
impl TailoredIntelligenceApi for TailoredIntelligenceApiClient {
    async fn get_events_body(
        &self,
        params: GetEventsBodyParams,
    ) -> Result<Vec<i32>, Error<GetEventsBodyError>> {
        let GetEventsBodyParams { id } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/ti/events/entities/events-full-body/v2",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.query(&[("id", &id.to_string())]);
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `Vec&lt;i32&gt;`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `Vec&lt;i32&gt;`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<GetEventsBodyError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn get_events_entities(
        &self,
        params: GetEventsEntitiesParams,
    ) -> Result<models::DomainEventEntitiesResponse, Error<GetEventsEntitiesError>> {
        let GetEventsEntitiesParams { body } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/ti/events/entities/events/GET/v2",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&body);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::DomainEventEntitiesResponse`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::DomainEventEntitiesResponse`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<GetEventsEntitiesError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn get_rules_entities(
        &self,
        params: GetRulesEntitiesParams,
    ) -> Result<models::DomainRuleEntitiesResponse, Error<GetRulesEntitiesError>> {
        let GetRulesEntitiesParams { body } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/ti/rules/entities/rules/GET/v2",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&body);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::DomainRuleEntitiesResponse`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::DomainRuleEntitiesResponse`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<GetRulesEntitiesError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn query_events(
        &self,
        params: QueryEventsParams,
    ) -> Result<models::DomainQueryResponse, Error<QueryEventsError>> {
        let QueryEventsParams {
            offset,
            limit,
            sort,
            filter,
            q,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/ti/events/queries/events/v2",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = offset {
            local_var_req_builder =
                local_var_req_builder.query(&[("offset", &param_value.to_string())]);
        }
        if let Some(ref param_value) = limit {
            local_var_req_builder =
                local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = sort {
            local_var_req_builder =
                local_var_req_builder.query(&[("sort", &param_value.to_string())]);
        }
        if let Some(ref param_value) = filter {
            local_var_req_builder =
                local_var_req_builder.query(&[("filter", &param_value.to_string())]);
        }
        if let Some(ref param_value) = q {
            local_var_req_builder = local_var_req_builder.query(&[("q", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::DomainQueryResponse`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::DomainQueryResponse`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<QueryEventsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn query_rules(
        &self,
        params: QueryRulesParams,
    ) -> Result<models::DomainQueryResponse, Error<QueryRulesError>> {
        let QueryRulesParams {
            offset,
            limit,
            sort,
            filter,
            q,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/ti/rules/queries/rules/v2",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = offset {
            local_var_req_builder =
                local_var_req_builder.query(&[("offset", &param_value.to_string())]);
        }
        if let Some(ref param_value) = limit {
            local_var_req_builder =
                local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = sort {
            local_var_req_builder =
                local_var_req_builder.query(&[("sort", &param_value.to_string())]);
        }
        if let Some(ref param_value) = filter {
            local_var_req_builder =
                local_var_req_builder.query(&[("filter", &param_value.to_string())]);
        }
        if let Some(ref param_value) = q {
            local_var_req_builder = local_var_req_builder.query(&[("q", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::DomainQueryResponse`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::DomainQueryResponse`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<QueryRulesError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`TailoredIntelligenceApi::get_events_body`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetEventsBodyError {
    Status400(String),
    Status403(),
    Status429(models::MsaReplyMetaOnly),
    Status500(Vec<i32>),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`TailoredIntelligenceApi::get_events_entities`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetEventsEntitiesError {
    Status400(models::DomainEventEntitiesResponse),
    Status403(),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::DomainEventEntitiesResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`TailoredIntelligenceApi::get_rules_entities`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetRulesEntitiesError {
    Status400(models::DomainRuleEntitiesResponse),
    Status403(),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::DomainRuleEntitiesResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`TailoredIntelligenceApi::query_events`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QueryEventsError {
    Status400(models::DomainQueryResponse),
    Status403(),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::DomainQueryResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`TailoredIntelligenceApi::query_rules`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QueryRulesError {
    Status400(models::DomainQueryResponse),
    Status403(),
    Status429(models::MsaReplyMetaOnly),
    Status500(models::DomainQueryResponse),
    UnknownValue(serde_json::Value),
}
