/*
 * CrowdStrike API Specification
 *
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: 2026-01-28T00:00:04Z
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiNotificationChannelV2CreateRequest {
    #[serde(rename = "config_name")]
    pub config_name: String,
    #[serde(rename = "params")]
    pub params: serde_json::Value,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "config_id", skip_serializing_if = "Option::is_none")]
    pub config_id: Option<String>,
}

impl ApiNotificationChannelV2CreateRequest {
    pub fn new(
        config_name: String,
        params: serde_json::Value,
        r#type: Type,
    ) -> ApiNotificationChannelV2CreateRequest {
        ApiNotificationChannelV2CreateRequest {
            config_name,
            params,
            r#type,
            config_id: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "email")]
    Email,
    #[serde(rename = "slack")]
    Slack,
    #[serde(rename = "pagerduty")]
    Pagerduty,
    #[serde(rename = "webhook")]
    Webhook,
    #[serde(rename = "ms_teams")]
    MsTeams,
}

impl Default for Type {
    fn default() -> Type {
        Self::Email
    }
}
