/*
 * CrowdStrike API Specification
 *
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: 2026-01-28T00:00:04Z
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::experimental::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CaohuntingapiHuntingGuideEntity {
    #[serde(rename = "category")]
    pub category: models::CaohuntingapiGuideCategory,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "languages")]
    pub languages: Vec<String>,
    #[serde(rename = "last_updated_at")]
    pub last_updated_at: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "adversaries", skip_serializing_if = "Option::is_none")]
    pub adversaries: Option<Vec<String>>,
    #[serde(rename = "ai_description", skip_serializing_if = "Option::is_none")]
    pub ai_description: Option<String>,
    #[serde(
        rename = "ai_short_description",
        skip_serializing_if = "Option::is_none"
    )]
    pub ai_short_description: Option<String>,
    #[serde(rename = "cql_query_count", skip_serializing_if = "Option::is_none")]
    pub cql_query_count: Option<i32>,
    #[serde(rename = "environments", skip_serializing_if = "Option::is_none")]
    pub environments: Option<Vec<String>>,
    #[serde(rename = "hunt_count", skip_serializing_if = "Option::is_none")]
    pub hunt_count: Option<i32>,
    #[serde(rename = "hunt_filter", skip_serializing_if = "Option::is_none")]
    pub hunt_filter: Option<String>,
    #[serde(rename = "malware_families", skip_serializing_if = "Option::is_none")]
    pub malware_families: Option<Vec<String>>,
    #[serde(rename = "mitre", skip_serializing_if = "Option::is_none")]
    pub mitre: Option<Vec<models::CaohuntingapiMitreData>>,
}

impl CaohuntingapiHuntingGuideEntity {
    pub fn new(
        category: models::CaohuntingapiGuideCategory,
        description: String,
        id: String,
        languages: Vec<String>,
        last_updated_at: String,
        name: String,
    ) -> CaohuntingapiHuntingGuideEntity {
        CaohuntingapiHuntingGuideEntity {
            category,
            description,
            id,
            languages,
            last_updated_at,
            name,
            adversaries: None,
            ai_description: None,
            ai_short_description: None,
            cql_query_count: None,
            environments: None,
            hunt_count: None,
            hunt_filter: None,
            malware_families: None,
            mitre: None,
        }
    }
}
