/*
 * CrowdStrike API Specification
 *
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: 2026-01-28T00:00:04Z
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::experimental::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CorrelationrulesapiRuleV1 {
    #[serde(rename = "api_client_id")]
    pub api_client_id: String,
    #[serde(rename = "created_on")]
    pub created_on: String,
    #[serde(rename = "customer_id")]
    pub customer_id: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "last_updated_on")]
    pub last_updated_on: String,
    #[serde(rename = "mitre_attack")]
    pub mitre_attack: Vec<models::CorrelationrulesapiMitreAttackMappingV1>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "operation")]
    pub operation: models::CorrelationrulesapiRuleOperationV1,
    #[serde(rename = "search")]
    pub search: models::CorrelationrulesapiRuleSearchV1,
    #[serde(rename = "severity")]
    pub severity: i32,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "status_msg")]
    pub status_msg: String,
    #[serde(rename = "tactic")]
    pub tactic: String,
    #[serde(rename = "technique")]
    pub technique: String,
    #[serde(rename = "template_id")]
    pub template_id: String,
    #[serde(rename = "updated_by_api_client_id")]
    pub updated_by_api_client_id: String,
    #[serde(rename = "updated_by_user_id")]
    pub updated_by_user_id: String,
    #[serde(rename = "updated_by_user_uuid")]
    pub updated_by_user_uuid: String,
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "user_uuid")]
    pub user_uuid: String,
    #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
    pub author: Option<String>,
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "executor_rule_id", skip_serializing_if = "Option::is_none")]
    pub executor_rule_id: Option<String>,
    #[serde(
        rename = "guardrail_notifications",
        skip_serializing_if = "Option::is_none"
    )]
    pub guardrail_notifications: Option<Vec<models::CorrelationrulesapiRuleNotificationsV1>>,
    #[serde(rename = "last_execution", skip_serializing_if = "Option::is_none")]
    pub last_execution: Option<models::CorrelationrulesapiRuleLastExecutionV1>,
    #[serde(rename = "next_execution_on", skip_serializing_if = "Option::is_none")]
    pub next_execution_on: Option<String>,
    #[serde(rename = "notifications", skip_serializing_if = "Option::is_none")]
    pub notifications: Option<Vec<models::CorrelationrulesapiRuleNotificationsV1>>,
    #[serde(rename = "rule_id", skip_serializing_if = "Option::is_none")]
    pub rule_id: Option<String>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<i32>,
}

impl CorrelationrulesapiRuleV1 {
    pub fn new(
        api_client_id: String,
        created_on: String,
        customer_id: String,
        id: String,
        last_updated_on: String,
        mitre_attack: Vec<models::CorrelationrulesapiMitreAttackMappingV1>,
        name: String,
        operation: models::CorrelationrulesapiRuleOperationV1,
        search: models::CorrelationrulesapiRuleSearchV1,
        severity: i32,
        status: String,
        status_msg: String,
        tactic: String,
        technique: String,
        template_id: String,
        updated_by_api_client_id: String,
        updated_by_user_id: String,
        updated_by_user_uuid: String,
        user_id: String,
        user_uuid: String,
    ) -> CorrelationrulesapiRuleV1 {
        CorrelationrulesapiRuleV1 {
            api_client_id,
            created_on,
            customer_id,
            id,
            last_updated_on,
            mitre_attack,
            name,
            operation,
            search,
            severity,
            status,
            status_msg,
            tactic,
            technique,
            template_id,
            updated_by_api_client_id,
            updated_by_user_id,
            updated_by_user_uuid,
            user_id,
            user_uuid,
            author: None,
            comment: None,
            description: None,
            executor_rule_id: None,
            guardrail_notifications: None,
            last_execution: None,
            next_execution_on: None,
            notifications: None,
            rule_id: None,
            state: None,
            r#type: None,
            version: None,
        }
    }
}
